<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Eagle_BIM_Blog_Detail_TOC_Widget extends \Elementor\Widget_Base {

	public function get_name() {
		return 'eagle-bim-blog-detail-toc';
	}

	public function get_title() {
		return __( 'Blog Detail TOC', 'eagle-bim-widgets' );
	}

	public function get_icon() {
		return 'eicon-list-bullet';
	}

	public function get_categories() {
		return [ 'eagle-bim-blog' ];
	}

	protected function register_controls() {
		$this->start_controls_section(
			'section_content',
			[
				'label' => __( 'Content', 'eagle-bim-widgets' ),
				'tab'   => \Elementor\Controls_Manager::TAB_CONTENT,
			]
		);

		$this->add_control(
			'toc_title',
			[
				'label'   => __( 'TOC Title', 'eagle-bim-widgets' ),
				'type'    => \Elementor\Controls_Manager::TEXT,
				'default' => __( 'Table of Contents', 'eagle-bim-widgets' ),
			]
		);

		$this->end_controls_section();
	}

	protected function render() {
		$settings = $this->get_settings_for_display();
		?>
		<div class="eb-toc-box">
			<div class="eb-toc-header">
				<span class="eb-toc-header-label"><?php echo esc_html( $settings['toc_title'] ); ?></span>
				<span class="eb-toc-header-line"></span>
			</div>
			<div class="eb-toc-body">
				<ul class="eb-toc-list" id="eb-blog-toc">
					<!-- Generated by JS -->
				</ul>
			</div>
		</div>
		<?php
	}
}
