<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Eagle_BIM_Blog_Detail_Mobile_TOC_Widget extends \Elementor\Widget_Base {

	public function get_name() {
		return 'eagle-bim-blog-detail-mobile-toc';
	}

	public function get_title() {
		return __( 'Blog Detail Mobile TOC', 'eagle-bim-widgets' );
	}

	public function get_icon() {
		return 'eicon-list-bullet';
	}

	public function get_categories() {
		return [ 'eagle-bim-blog' ];
	}

	protected function register_controls() {
		$this->start_controls_section(
			'section_content',
			[
				'label' => __( 'Content', 'eagle-bim-widgets' ),
				'tab'   => \Elementor\Controls_Manager::TAB_CONTENT,
			]
		);

		$this->add_control(
			'toc_title',
			[
				'label'   => __( 'TOC Title', 'eagle-bim-widgets' ),
				'type'    => \Elementor\Controls_Manager::TEXT,
				'default' => __( 'Contents', 'eagle-bim-widgets' ),
			]
		);

		$this->end_controls_section();
	}

	protected function render() {
		$settings = $this->get_settings_for_display();
		?>
		<div class="eb-mobile-toc-container">
			<div class="eb-mobile-toc-trigger" id="eb-mobile-toc-trigger">
				<span class="eb-mobile-toc-label"><?php echo esc_html( $settings['toc_title'] ); ?></span>
				<span class="eb-mobile-toc-icon">
					<svg width="12" height="8" viewBox="0 0 12 8" fill="none" xmlns="http://www.w3.org/2000/svg">
						<path d="M1 1L6 6L11 1" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
					</svg>
				</span>
			</div>
			<div class="eb-mobile-toc-dropdown" id="eb-mobile-toc-dropdown">
				<ul class="eb-toc-list eb-mobile-toc-list">
					<!-- Generated by JS -->
				</ul>
			</div>
		</div>
		<?php
	}
}
